djangoProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path

from products.views import ProductListView, ProductCategoryListView

app_name = 'products'

urlpatterns = [
    path('', ProductListView.as_view(), name='index'),
    path('category/<int:pk>/', ProductCategoryListView.as_view(), name='category'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hitcount/models.py
from django.contrib.auth.models import User
from django.db import models


class HitCount(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)
    path = models.CharField(max_length=512)
    hits = models.IntegerField(default=1)

    def __str__(self):
        return f'{self.path} ({self.hits})'

    def save(self, *args, **kwargs):
        print(self)
        return super().save(*args, **kwargs)

products/models.py
from django.db import models
from django.contrib.sites.models import Site
from django.contrib.sites.managers import CurrentSiteManager
from django.db.models import Manager

from djangoProject.settings.base import MEDIA_ROOT


class Product(models.Model):
    name = models.CharField(max_length=128, verbose_name='название')
    measure = models.CharField(max_length=128, verbose_name='единица измерения')
    price = models.DecimalField(max_digits=12, decimal_places=2, verbose_name='цена')
    receipt_date = models.DateField(auto_now_add=True, verbose_name='дата поступления')
    supplier = models.CharField(max_length=128, verbose_name='поставщик')
    category = models.ManyToManyField('Category')
    image = models.ImageField(upload_to='product_images', verbose_name='изображение', default='default_product.png')
    sites = models.ManyToManyField(Site)
    objects = Manager()
    on_site = CurrentSiteManager('sites')

    def __str__(self):
        return self.name


class Category(models.Model):
    name = models.CharField(max_length=128, verbose_name='название')
    description = models.TextField(blank=True, null=True)
    site = models.ForeignKey(Site, on_delete=models.CASCADE, null=True)
    objects = Manager()
    on_site = CurrentSiteManager('site')

    class Meta:
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name

hitcount/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.contrib.sites.shortcuts import get_current_site
from django.views.generic import ListView
from django.views.generic.base import ContextMixin

from products.models import Product, Category


class PageContextMixin(ContextMixin):
    title = ''
    categories = Category.on_site.all()

    def get_context_data(self, **kwargs):
        context = super(PageContextMixin, self).get_context_data(**kwargs)
        context['title'] = self.title
        context['categories'] = self.categories
        return context


class ProductListView(PageContextMixin, ListView):
    model = Product
    title = 'products'
    template_name = 'goods_list.html'
    ordering = ['-receipt_date']
    queryset = Product.on_site.prefetch_related('category').all()


class ProductCategoryListView(PageContextMixin, ListView):
    model = Product
    title = 'products'
    template_name = 'products_category.html'
    ordering = ['-receipt_date']

    def get_queryset(self):
        category_pk = self.kwargs.get('pk')
        self.title = Category.on_site.filter(id=category_pk).first().name
        if category_pk:
            return Product.on_site.filter(category__in=[category_pk])
        else:
            return Product.on_site.all()

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <link href="{% static  'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static  'css/main.css' %}" rel="stylesheet">
</head>
<body>
<div class="container-lg">
    {% include 'inc_categories.html' %}
    {% block content %}
    {% endblock %}
</div>
<script src="{% static  'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

templates/goods_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Изображение</th>
            <th scope="col">Название</th>
            <th scope="col">Единица измерения</th>
            <th scope="col">Цена</th>
            <th scope="col">Дата поступления</th>
            <th scope="col">Поставщик</th>
            <th scope="col">Категории</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><img alt="no image" src="{{ object.image.url }}"/></td>
                <td>{{ object.name|title }}</td>
                <td>{{ object.measure }}</td>
                <td>{{ object.price }}</td>
                <td>{{ object.receipt_date }}</td>
                <td>{{ object.supplier|title }}</td>
                <td>{{ object.supplier|title }}</td>
                <td>
                    <ul>
                        {% for category in object.category.all %}
                            <li>{{ category.name }}</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <button id="add-product" type="button" class="btn btn-primary">Добавить товар</button>
{% endblock %}

templates/inc_categories.html
<div class="categories">
    <nav class="navbar navbar-light" style="background-color: #e3f2fd;">
        {% with request.resolver_match as req_info %}
            <a class="navbar-brand {% if req_info.url_name == 'index' %}active{% endif %}"
               href="{% url 'products:index' %}">All Products</a>
            {% for category in categories %}
                <a class="navbar-brand {% if req_info.url_name == 'category' and req_info.kwargs.pk == category.id %}active{% endif %}"
                   href="{% url 'products:category' category.id %}">{{ category.name }}</a>
            {% endfor %}
        {% endwith %}
    </nav>
</div>

templates/products_category.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
    <table class="table">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th scope="col">Изображение</th>
            <th scope="col">Название</th>
            <th scope="col">Единица измерения</th>
            <th scope="col">Цена</th>
            <th scope="col">Дата поступления</th>
            <th scope="col">Поставщик</th>
        </tr>
        </thead>
        <tbody>
        {% for object in object_list %}
            <tr>
                <th scope="row">{{ forloop.counter }}</th>
                <td><img alt="no image" src="{{ object.image.url }}"/></td>
                <td>{{ object.name|title }}</td>
                <td>{{ object.measure }}</td>
                <td>{{ object.price }}</td>
                <td>{{ object.receipt_date }}</td>
                <td>{{ object.supplier|title }}</td>
                <td>{{ object.supplier|title }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    <button id="add-product" type="button" class="btn btn-primary">Добавить товар</button>
{% endblock %}